# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-03 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review_system', '0003_auto_20180128_0743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviews', models.TextField(max_length=1000, null=True)),
                ('rating', models.FloatField(default=0.0)),
                ('user_locations', models.TextField(max_length=200, null=True)),
                ('sentiment', models.FloatField(default=0.0)),
            ],
        ),
        migrations.RemoveField(
            model_name='map',
            name='location',
        ),
        migrations.RemoveField(
            model_name='map',
            name='placeId',
        ),
        migrations.AddField(
            model_name='map',
            name='address',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='map',
            name='place_id',
            field=models.TextField(max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='reviews',
            name='place_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review_system.Map'),
        ),
    ]
